### ISSUE TITLE
Ошибка CORB блокирует загрузку pyscript.css и другие ресурсы

### ISSUE THREAD

**Issue by nZiben** [glebmikha/ab-test-calculator-by-gleb-mikhaylov#1]
При загрузке страницы возникает ошибка Cross-Origin Read Blocking (CORB), которая блокирует кросс-доменные ответы. Кроме того, не удается загрузить файл стилей pyscript.css.

Ошибка в консоли:
Response was blocked by CORB (Cross-Origin Read Blocking)
Cross-Origin Read Blocking (CORB) blocked a cross-origin response.
Не удалось загрузить pyscript.css:
This page failed to load a stylesheet from a URL.
Source: ab-test-calculator-by-gleb-mikhaylov/:78
![image](https://github.com/user-attachments/assets/79954f78-567b-4058-b750-53728d7c1782)

**Comment by glebmikha** [comment]
А ты знаешь как это починить? Я что-то с ходу не могу разобраться. Если знаешь, что там не так, мб сделаешь pull request? Буду очень признателен

**Comment by glebmikha** [comment]
Я в итоге сам разобрался. PyScript обновился и пришлось переписать под новый стиль.

**Comment by glebmikha** [comment]
Закрываю
